---
title: "Assignment 1"
author: "Rose Porta, Hasmik Grigoryan, Sandani Kumanayake, Hanyu Xiao"
date: "2023-09-12"
output: pdf_document
bibliography: "`r rbbt::bbt_write_bib('tpa.bib', overwrite = TRUE)`"
csl: "harvard-cite-them-right.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

In 2022 more than 2.7million flights were operated from airports in the United States generating a record amout of more than 270billion US dollars. [@OnTimePerformanceReporting] [@statistaresearchdepartmentTotalOperatingRevenue2023] Despite the significant increase in revenue there have also been a large percentage of flight delays in the recent years. In 2022, more than 20% of departures, and arrivals were delayed. [@OnTimePerformanceReporting] This is not only costly to the aviation industry but can cause a significant annoyance to customers. Over the course of this semester we will try to find trends in flight delays, analyze the toll it takes on the industry and hypothesize potential causes and solutions. 

## At a Glance

Before delving into statistical analysis we should look at the trends visible at a glance.

In 2022, the percentage of delays doubled from the two years prior. While we know that the years 2020-2021 were outliers in terms of travel due to the COVID-19 pandemic, we can also see that the increase in delays is still considerably large from the years 2018-2019 (around 2-3% increase). [@OnTimePerformanceReporting]

Within the year 2022 the largest percentage of delays occur in the summer months (22-23% as opposed to the average of 20%). A larger number of flights operate during June-August as well. This may suggest that the delays are a result of overcrowding. The least percentage of flights are delayed in the months of September and October (~16%). [@OnTimePerformanceMarketing]

Trends such as these have given birth to many articles informing travelers of the best times to travel, airlines to choose, and metrics to consider when booking flights. From avoiding layovers, to booking the first flight of the day, there are many tips and tricks recommended. An article on NerdWallet shows results comparing many airlines and points out that some are the clear airlines to avoid. JetBlue lands flights on time only 60% of the time while Delta Airlines is on time almost 80% of the time. [@frenchHowBookFlight]

Overall, it is clear that flight delays have increased in the recent years. The amount of trouble this causes millions of travelers per year gives an opportunity for airports and airlines to stand out with their customer service. Tampa Internation Airport is one of the airports that has perhaps capitalized on this inconvenience.

## Tampa International Airport (TPA)

Tampa International Airport (TPA) located in Tampa, Florida is a large U.S. airport with roughly 21 million passengers, 459 million pieces of cargo, and 26 million pieces of mail traveling through it in 2022.[@FactsStatisticsFinancials] It offers flights to more than 90 destinations, with the most popular domestic destinations being Atlanta, GA; Charlotte, NC; Denver, CO; Chicago, IL, and Dallas, TX. [@FactsStatisticsFinancials] [@RITABTSTranstats] It is ranked 23rd largest airport in the U.S. [@FactsStatisticsFinancials] On average, there are 60,000 passengers traveling through per day and 550 departing and arriving flights (combined). [@TampaInternationalAirport2023] The month with the most flights in 2022 was March, while the fewest flights happened in September. The top airlines servicing TPA are Southwest Airlines, Delta Air Lines, American Airlines, United Airlines, Spirit Airlines, Frontier Airlines and JetBlue Airways.[@FactsStatisticsFinancials] The airport is publicly owned by the Hillsborough County Aviation Authority (HCAA), and all administrative decisions are made through a board of directors. [@AirportAdministrationTampa]

At first glance, TPA appears to be close to the national average with respect to flight delays. In 2022, 74% of domestic flights departed on-time (defined as within 15 minutes of scheduled time), with an average delay time of 70 minutes for those with delays. For domestic arrivals, 71% arrived on-time with an average delay time of 64 minutes for delayed flights. 3.5% of domestic flights were canceled in 2022.[@RITABTSTranstats]

TPA is known for its high rankings in customer satisfaction. In 2022, JD Power’s Airport Satisfaction Study ranked TPA number one in the U.S. based on its high quality terminal facilities, airport arrival/departure processes; baggage claim; security check; check-in/baggage check; and food, beverage and retail.[@PowerNamesTPA] In July 2023, a study by FloridaRentals.com ranked TPA third best in Florida based on its low percentage of delays and cancellations along with other factors.[@reportsStudyListsTampa2023] Most recently, USA TODAY has named TPA a finalist in their annual 10Best Readers Choice Awards program for 2023. The final winner will be determined by public voting.[@TPABestLarge]

Beyond excellent customer experience, a unique element of TPA is its extensive public art collection.[@PublicArtCollection] Recently, a twenty-one foot tall flamingo statue created by artist Matthew Mazzotta, which lives in the airport, received a prestigious international art award.[@TampaInternationalAirport]

Furthermore, TPA is making active efforts toward environmental sustainability. 42% of planes run on alternative fuels including CNG, electric and hybrid. The airport hosts 15 electric vehicle charging stations for public use and gives preferential parking to people with alternative fuel vehicles. They also use reclaimed water for landscape irrigation and cooling towers. Moreover, TPA has reduced electricity consumption by 10% per passenger since 2011. The airport administration has a comprehensive plan for extending sustainability efforts even further over the next several years.[@SustainabilityTampaInternational]

## References

